domain_path: /home/pruparel/Projects/FPGA/camera/application/camera_platform/export/camera_platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
